#!/bin/bash

echo "[***] Creating $IMAGE_NAME manifest"
# MANIFESTS=$(for $ARCH in $ARCHITECTURES; do printf "%s:%s " $DOCKER_REPO $ARCH; done)
# docker manifest create $IMAGE_NAME $MANIFESTS

cat <<EOF > manifest.yaml
image: $IMAGE_NAME
manifests:
$(for ARCH in $ARCHITECTURES; do \
  PLATFORM="PLATFORM_$(echo $ARCH | awk '{print toupper($0)}')"; \
  OS=$(echo ${!PLATFORM} | awk 'BEGIN { FS = "/" };{print $1}'); \
  ARCHITECTURE=$(echo ${!PLATFORM} | awk 'BEGIN { FS = "/" };{print $2}'); \
  VARIANT=$(echo ${!PLATFORM} | awk 'BEGIN { FS = "/" };{print $3}'); \
  printf "  - image: %s:%s\n" $DOCKER_REPO $ARCH; \
  printf "    platform:\n"; \
  printf "      architecture: %s\n" $ARCHITECTURE; \
  printf "      os: %s\n" $OS; \
  test ! -z "$VARIANT" && printf "      variant: %s\n" $VARIANT; \
  done)
EOF
