#!/bin/bash

# check required variables and bail if not present
if [[ -z ${ARCHITECTURES} ]]; then
  echo "[***] Please set the ARCHITECTURES variable with the desired architectures to build"
  exit 1
fi

for ARCH in ${ARCHITECTURES}; do
  PLATFORM="PLATFORM_$(echo $ARCH | awk '{print toupper($0)}')"
  if [[ -z ${!PLATFORM} ]]; then
    echo "[***] Please set ${PLATFORM} with the target platform in docker-buildx format"
    exit 1
  fi
done

# thanks https://github.com/se1exin/
# Register qemu-*-static for all supported processors except the
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset
