#!/bin/bash

echo "[***] Pushing $IMAGE_NAME manifest"
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool
./manifest-tool push from-spec manifest.yaml
